services:
    pimcore-app:
        build: .
        ports:
            - "5000:80"
        depends_on:
            db:
                condition: service_healthy

    db:
        image: mariadb:10.7
        working_dir: /application
        command:
            [
                mysqld,
                --character-set-server=utf8mb4,
                --collation-server=utf8mb4_unicode_ci,
                --innodb-file-per-table=1,
            ]
        volumes:
            - pimcore-database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=pimcore_learning_database
            - MYSQL_USER=pimcore
            - MYSQL_PASSWORD=pimcore

        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "db", "-uroot", "-proot"]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s

volumes:
    pimcore-database:
